# Automatically generated by configure - do not modify
TARGET_DIR=i386-s2e-softmmu
S2E_SRC_PATH=/home/wb/work/workspace/prophet
S2E_BUILD_PATH=/home/wb/work/build/prophet
LLVM_BUILD_PATH=/home/wb/work/build/llvm3.2
BUNDLE_NAME=simplebundle
